name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Set Day of Week
        id: set_day
        run: echo "DAY_OF_WEEK=$(date +%A)" >> $GITHUB_ENV
      - name: Greetings
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Jon
