name: Hello World

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: false
        default: 'World'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1 # Keeps your builds from running too long
    steps:
      - name: Greeting
        run: |
          echo "Hello ${{ inputs.who-to-greet }}!"
